#!/usr/bin/env python3 

# Vraag een gebruiker om hun leeftijd
age = int(input("What is your age?")) 

# Kijk of deze gebruiker volwassen is
if age >= 18:
  print("Volwassen")
  
else:
  print("Minderjarig") 

